
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: satoshy
  pool: 5
  host: localhost

development:
  <<: *default
  database: notes_development

test:
  <<: *default
  database: notes_test

production:
  <<: *default
  database: notes_production
  username: notes
  password: <%= ENV['NOTES_DATABASE_PASSWORD'] %>
